//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class base_student
    {
        [Key]
        public long student_id { get; set; }
        [MaxLength(100)]
        public string student_name { get; set; }
        [MaxLength(100)]
        public string sex { get; set; }
        [MaxLength(100)]
        public string birthday { get; set; }
        [MaxLength(10)]
        public string height { get; set; }
        [MaxLength(10)]
        public string weight { get; set; }
        [MaxLength(100)]
        public string address { get; set; }
        [MaxLength(10)]
        public long class_id { get; set; }
        [MaxLength(10)]
        public long school_id { get; set; }
        [MaxLength(100)]
        public string bracelet_id { get; set; }
        public System.DateTime create_time { get; set; }
        public System.DateTime update_time { get; set; }
        [MaxLength(100)]
        public string father_name { get; set; }
        [MaxLength(100)]
        public string father_phone { get; set; }
        [MaxLength(100)]
        public string mother_name { get; set; }
        [MaxLength(100)]
        public string mother_phone { get; set; }
        [MaxLength(255)]
        public string description { get; set; }
    }
}
