//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Class
    {
        public int ClassID { get; set; }
        public Nullable<int> SchoolID { get; set; }

        [MaxLength(100)]
        public string ClassName { get; set; }
        [MaxLength(100)]
        public string ClassType { get; set; }
        public Nullable<int> State { get; set; }
        [MaxLength(100)]

        public string Grade { get; set; }
    }
}
