//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course
    {
        public System.Guid ID { get; set; }
        public int CourseID { get; set; }
        public Nullable<int> ClassID { get; set; }
        public string CourseName { get; set; }
        public string CourseType { get; set; }
        public string CourseDescription { get; set; }
        public Nullable<System.DateTime> TimeFrom { get; set; }
        public Nullable<System.DateTime> TimeTo { get; set; }
        public Nullable<int> Weekly { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<int> Term { get; set; }
        public Nullable<System.DateTime> EffectFrom { get; set; }
        public Nullable<System.DateTime> EffectTo { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> State { get; set; }
    }
}
