//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class School
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Lev { get; set; }
        public string Type { get; set; }
        public string Address { get; set; }
        public string Tel { get; set; }
        public string Contacts { get; set; }
        public string Charge { get; set; }
        public string Descp { get; set; }
        public Nullable<float> Lan { get; set; }
        public Nullable<float> Lat { get; set; }
        public Nullable<int> Statue { get; set; }
        public string Proviance { get; set; }
        public string City { get; set; }
        public string Area { get; set; }
    }
}
