//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Student
    {
        public int StudentID { get; set; }
        public int ClassID { get; set; }
        [MaxLength(100)]
        public string Name { get; set; }
        public Nullable<bool> Sex { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        [MaxLength(100)]
        public string Phone { get; set; }
        [MaxLength(100)]
        public string Address { get; set; }
        [MaxLength(100)]
        public string Proviance { get; set; }
        [MaxLength(100)]
        public string City { get; set; }
        [MaxLength(100)]
        public string Area { get; set; }
        [MaxLength(100)]
        public string FaceImgName { get; set; }
        public Nullable<System.Guid> PersistedFaceId { get; set; }
        public Nullable<System.Guid> PersistedFaceIdSchool { get; set; }
        public Nullable<int> State { get; set; }
    }
}
