//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public System.Guid UserID { get; set; }
        public string Name { get; set; }
        public string Password { get; set; }
        public Nullable<int> RoleID { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string QQ { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string District { get; set; }
        public string City { get; set; }
        public Nullable<int> SchoolID { get; set; }
        public Nullable<int> ClassID { get; set; }
        public string NickName { get; set; }
        public string Picture { get; set; }
    }
}
