//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewProject.Data.Model
{

    public partial class UserDevice : Entity
    {
        public int UserId { get; set; }
        public System.DateTime CreateTime { get; set; }
        public System.DateTime ActiveTime { get; set; }
        public System.DateTime ExpiredTime { get; set; }
        public int DeviceType { get; set; }
        public string SessionKey { get; set; }
    }
}
